### ISSUE TITLE
Get rid of keys duplication for `SmtLeaf::Multiple`

### ISSUE THREAD

**Issue by polydez** [0xPolygonMiden/crypto#360]
`Smt` supports for various leaf types, and `Multiple` is one of them (leaf with multiple values):

```rust
Multiple(Vec<(RpoDigest, Word)>),
```

According to implementation, it is guarantied that all values in such leaf have the same key. But we duplicate that key for all values in the leaf.

My proposal is to refactor this in order to have only single key for multiple entries:

```rust
Multiple {
    key: RpoDigest, 
    values: Vec<Word>,
},

// or just:

Multiple((RpoDigest, Vec<Word>)),
```

If we choose the first approach, we can also refactor `Single` from tuple to struct.

**Comment by bobbinth** [comment]
I think maybe the documentation needs to be improved here because the key-value pairs are actually distinct. What is the same is the most significant element of the key. Basically, the key consists of 4 elements and for `Multiple` leaf, `key[3]` is the same for all key-value pairs, but the remaining elements of the key could be different.

**Comment by polydez** [comment]
Ah, my bad, thank you for clarification! Closed
